- name: Install nginx
  ansible.builtin.apt:
    name: "{{ nginx_package }}"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
    state: present

- name: Enable service nginx
  ansible.builtin.systemd:
    name: "{{ nginx_service_name }}"
    enabled: true
    state: started

- name: Install required PHP packages
  apt:
    name: "{{ php_packages }}"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
    state: present

- name: Update PHP configuration
  ansible.builtin.lineinfile:
    path: "{{ php_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ php_config_updates }}"
  notify:
    - Restart nginx

- name: Create magento configuration
  ansible.builtin.template:
    src: "{{ magento_template_src }}"
    dest: "{{ magento_config_dest }}"
  notify:
    - Restart nginx
