---
# vars file for nginx
nginx_package: "nginx"
cache_valid_time: 86400
nginx_service_name: "nginx"
php_packages:
  - php 
  - php-dev
  - php-fpm
  - php-bcmath
  - php-intl
  - php-soap
  - php-zip
  - php-curl
  - php-mbstring
  - php-mysql
  - php-gd
  - php-xml
php_config_path: "/etc/php/8.1/cli/php.ini"
php_config_updates:
  - regexp: 'max_execution_time'
    line: 'max_execution_time = 3600'
  - regexp: 'memory_limit'
    line: 'memory_limit  = 512M'
  - regexp: 'upload_max_filesize'
    line: 'upload_max_filesize = 128M'
magento_template_src: "templates/magento2.conf.j2"
magento_config_dest: "/etc/nginx/conf.d/magento2.conf"

fastcgi_backend: "unix:/run/php/php8.1-fpm.sock"
listen_port: 80
server_name: "15.236.18.167"
mage_root: "/var/www/magento2"
include_path: "/var/www/magento2/nginx.conf.sample"