---
# tasks file for magento
- name: Set Magento Access Keys for Composer
  shell: echo -e 'yes\n' |composer global config http-basic.repo.magento.com be483e6a3c2c1558ee6aa660c33785db a764930458246dd5702d3dfa8ef8a555

- name: Create the Magento Open Source Project
  shell: echo -e 'yes\n' |composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.6 /var/www/magento2

- name: Set Files Permissions to g+w
  shell: find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
  args:
    chdir: /var/www/magento2

- name: Set Directories Permissions to g+ws
  shell: find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \;
  args:
    chdir: /var/www/magento2

- name: Set Files and Directories Group User
  file:
    dest: /var/www/magento2
    group: www-data
    recurse: yes

- name: Install Magento
  shell: |
    bin/magento setup:install \
      --base-url=http://15.236.40.152 \
      --db-host=localhost \
      --db-name=magentodb \
      --db-user=magentouser \
      --db-password=MyPassword \
      --admin-firstname=Admin \
      --admin-lastname=User \
      --admin-email=admin@your-domain.com \
      --admin-user=admin \
      --admin-password=admin123 \
      --language=en_US \
      --currency=USD \
      --timezone=America/Chicago \
      --use-rewrites=1
  args:
    chdir: /var/www/magento2

