- name: Download Composer Installer
  get_url:
    url: "{{ composer_installer_url }}"
    dest: "{{ composer_installer_dest }}"
    mode: "{{ composer_installer_mode }}"

- name: Install Composer using PHP
  shell: php {{ composer_installer_filename }}
  args:
    chdir: "{{ composer_installer_chdir }}"

- name: Move Composer File to /user/local/bin
  shell: mv {{ composer_installer_filename }} {{ composer_bin_location }}
  args:
    chdir: "{{ composer_installer_chdir }}"

- name: Create Symbolic Link
  file:
    src: "{{ composer_bin_location }}"
    dest: "{{ composer_symlink_location }}"
    owner: "{{ composer_symlink_owner }}"
    group: "{{ composer_symlink_group }}"
    state: link
