# tasks file for elasticsearch
- name: Download GPG key and save as .asc
  ansible.builtin.get_url:
    url: "{{ elasticsearch_gpg_url }}"
    dest: "{{ elasticsearch_gpg_dest }}"

- name: Import GPG key
  ansible.builtin.shell: |
    gpg --dearmor -o {{ elasticsearch_gpg_keyring_dest }} {{ elasticsearch_gpg_dest }}

- name: Add repository line to sources.list
  ansible.builtin.lineinfile:
    path: "{{ elasticsearch_repo_path }}"
    line: "{{ elasticsearch_repo_line }}"
    create: yes

- name: Install elasticsearch
  ansible.builtin.apt:
    name: "{{ elasticsearch_package_name }}"
    update_cache: yes
    force: true
    state: present

- name: Enable service elasticsearch
  ansible.builtin.systemd:
    name: "{{ elasticsearch_service_name }}"
    enabled: true
    state: started

- name: Update elasticsearch configuration
  ansible.builtin.lineinfile:
    path: "{{ elasticsearch_config_path }}"
    regexp: 'xpack.security.enable'
    line: '{{ elasticsearch_security_line }}'
  notify:
    - Restart elasticsearch
