---
# tasks file for elasticsearch
- name: Download GPG key and save as .asc
  ansible.builtin.get_url:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    dest: /tmp/elasticsearch-key.gpg

- name: Import GPG key
  ansible.builtin.shell: |
    gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg /tmp/elasticsearch-key.gpg

- name: Add repository line to sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/elastic-8.x.list
    line: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main'
    create: yes

- name: Install elasticsearch
  ansible.builtin.apt:
    name: elasticsearch
    update_cache: yes
    force: true
    state: present

- name: Enable service elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: started

- name: Update elasticsearch configuration
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'xpack.security.enable'
    line: 'xpack.security.enabled: false'
  notify:
    - Restart elasticsearch